name: Node.js CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

  
    runs-on: ubuntu-latest

    
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: back4app Deploy Action
        uses: heinrichcoetzee/back4app-deploy-action@v4
        with:
          project: "appnodedeploy"
<<<<<<< HEAD
          repo-token: ${{secrets.BACK4APP_API_KEY}}
=======
          accountKey: ${{secrets.BACK4APP_API_KEY}}

>>>>>>> b207934fed9b8af83cde17b03bd53703e512389d
